### ISSUE TITLE
Multiple keywords/tags are ignored

### ISSUE THREAD

**Issue by JAForbes** [achesco/extract-iptc#2]
If a photo has multiple tags it will have multiple instances of Keyword in the IPTC output.  

Unfortunately the current implementation replaces existing keywords them on each occurrence.

Would you accept a pull request that creates an array for Keywords specifically?

**Comment by achesco** [comment]
Please, check if last commit fixes it for your case.

**Comment by JAForbes** [comment]
@achesco the commit fixed the issues.  Thank you.
